# Generated by Django 2.1.1 on 2018-09-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180913_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='name',
            new_name='content',
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_ip',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
